services:
  postgres_db:
    image: postgres:15
    container_name: postgres_db
    env_file: ".env"
    environment:
      POSTGRES_USER: ${APP_CONFIG__DB__USER}
      POSTGRES_PASSWORD: ${APP_CONFIG__DB__PASSWORD}
      POSTGRES_DB: ${APP_CONFIG__DB__NAME}
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${APP_CONFIG__DB__USER} -d ${APP_CONFIG__DB__NAME}" ]
      interval: 10s
      retries: 5

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_app
    env_file: ".env"
    depends_on:
      postgres_db:
        condition: service_healthy
    environment:
      APP_CONFIG__DB__URL: ${APP_CONFIG__DB__URL}
    ports:
      - "8000:8000"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: postgres_db
      ADMINER_DESIGN: nette